# Generated by Django 4.2.10 on 2024-02-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_brandcars_alter_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='plate',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
